modified:   bin/drop

diff --git a/bin/drop b/bin/drop
--- a/bin/drop
+++ b/bin/drop
@@ -6,6 +6,7 @@
 # This is workaround for chrome not supporting shift+drag behavior
 
 # needs: yad, mpv, youtube-dl, socat, awk, mediainfo
+# wishes: jq
 
 # cli switches: -i, -l, -h
 
@@ -16,6 +17,7 @@ command -v youtube-dl >/dev/null 2>&1 || { echo "I need youtube-dl, exiting." >&
 command -v socat >/dev/null 2>&1 || { echo "I need socat, exiting." >&2; exit 1; }
 command -v awk >/dev/null 2>&1 || { echo "I need awk, exiting." >&2; exit 1; }
 command -v mediainfo >/dev/null 2>&1 || { echo "I need mediainfo, exiting." >&2; exit 1; }
+command -v jq >/dev/null 2>&1 || { echo "I would like jq for some cli stuff you can do." ; }
 
 # vars
 pipe="/tmp/pipe" && touch "$pipe"
@@ -52,7 +54,14 @@ awk_round () {
 whatPlaying () {
     
     # exit if pipe not working
-    echo '{ "command": ["get_property", "media-title"] }' | socat - "$pipe" >/dev/null 2>&1 || exit 
+    status="$(echo '{ "command": ["get_property", "mpv-version"] }' | socat - "$pipe" 2>/dev/null | jq -r .error)" 
+    
+    if [[  $status != "success" ]]; then
+    
+        echo "No."
+        exit 1
+    
+    fi
 
     # get data
     title="$(echo '{ "command": ["get_property", "media-title"] }' | socat - "$pipe" | jq -r .data )" 
