modified:   drop

diff --git a/bin/drop b/bin/drop
--- a/bin/drop
+++ b/bin/drop
@@ -8,7 +8,16 @@
 # needs: yad, mpv, youtube-dl, socat
 
 pipe="/tmp/pipe" && touch "$pipe"
+log="$HOME/.watched.m3u"
 
+# logging
+if ! [ -f "$log" ]; then
+    # start fresh
+    printf "#EXTM3U\n\n" > "$log" # If this fails, mpv can still play playlist without the header.
+fi
+touch "$log" || echo "Can't write to $log"
+
+# mpv and pipe
 isRunning () {
 
     # lets query whatever to see if the thing is already running
@@ -23,16 +32,35 @@ isRunning () {
     fi
 }
 
-#isRunning
-
+# action
 yad --on-top --no-buttons --title="drop urls here" --text="\n\n\nDROP" --geometry=200x200+50-50 --text-align=center --dnd | while read -r url
-# --width=200 --height=200 --undecorated 
 
-do
+    do
 
-    isRunning
-    echo "$url just droped"
-    echo "loadfile \"$url\" append-play" | socat - "$pipe"
-    [[ $url == http* ]] && youtube-dl -e "$url" && echo # if url, try to get url title
+        isRunning
+        
+        echo "$url just droped"
+        
+        # load stuff to mpv pipe
+        echo "loadfile \"$url\" append-play" | socat - "$pipe"
+        
+        # url or file
+        if [[ $url == http* ]] ; then 
+        
+            yt=$(youtube-dl -e "$url") && echo "$yt" && echo # if url, try to get url title
+            desc="$yt"
+        
+        else # assume its a file 
+        
+            desc="${url##*/}"
+        
+        fi
 
-done
+        # log
+        echo "#EXTINF:,$desc" >> "$log"
+        printf "%s\n\n" "$url" >> "$log"
+        
+        # reset vars
+        yt="" ; desc="" ; url=""
+        
+    done
